export const filterList = [
  {
    title: "Sector",
    name: "sector",
    options: [
      "Retail",
      "Manufacturing",
      "Energy",
      "Aerospace & defence",
      "Support services",
      "Environment",
      "Government",
      "Financial services",
      "Automotive",
      "Food & agriculture",
      "Information Technology",
      "Security",
      "Construction",
      "Transport",
      "Tourism & hospitality",
      "Healthcare",
      "Water",
      "Media & entertainment",
    ],
  },
  {
    title: "Topic",
    name: "topic",
    options: [
      "export",
      "gdp",
      "production",
      "battery",
      "gas",
      "oil",
      "growth",
      "energy",
      "unemployment",
      "transport",
      "climate",

      "finance",
      "vehicle",
      "policy",
      "resource",
      "electricity",
      "money",
      "technology",
      "biofuel",
      "security",
      "robot",
      "economic growth",
      "economy",
      "strategy",
      "industry",
      "terrorism",
      "power",
      "population",
      "politics",
      "demand",
      "plastic",
      "interest rate",
      "food",
      "investment",
      "building",
      "debt",
      "economic",
      "market",
      "trade",
      "artificial intelligence",
      "crisis",
      "asylum",
      "coal",
      "infrastructure",
      "bank",
      "war",
      "tension",
      "peak oil",
      "risk",
      "city",
      "revenue",
      "capital",
      "administration",
      "business",
      "work",
      "inflation",
      "gasoline",
      "shortage",
      "tourist",
      "emission",
      "government",
      "transportation",
      "consumption",
      "ice",
      "car",
      "aquaculture",
      "climate change",
      "software",
      "clothing",
      "worker",
      "gamification",
      "wealth",
      "agriculture",
      "data",
      "fossil fuel",
      "farm",
      "nuclear",
      "shale gas",
      "workforce",
      "automaker",
      "consumer",
      "fracking",
      "information",
      "Washington",
      "material",
      "tax",
      "brexit",
      "change",
      "3D",
      "greenhouse gas",
      "carbon",
      "storm",
      "election",
      "water",
      "factory",
      "communication",
      "pollution",
    ],
  },
  {
    title: "Region",
    name: "region",
    options: [
      "Northern America",
      "Western Africa",

      "Northern Africa",
      "Southern Africa",
      "Southern Asia",
      "World",
      "Eastern Europe",
      "Western Asia",
      "Eastern Asia",
      "Western Europe",
      "Europe",
      "South America",
      "South-Eastern Asia",
      "Oceania",
      "Africa",
      "Northern Europe",
      "Central Asia",
      "Eastern Africa",
      "Asia",
      "Southern Europe",
      "Central America",
      "Central Africa",
      "world",
    ],
  },
  {
    title: "End Year",
    name: "end_year",
    options: [
      2018, 2025, 2017, 2030, 2020, 2050, 2019, 2040, 2021, 2035, 2016, 2200,
      2024, 2022, 2028, 2046, 2026, 2027, 2041, 2055, 2126, 2036, 2034, 2051,
      2060,
    ],
  },
  {
    title: "Pestle",
    name: "pestle",
    options: [
      "Economic",
      "Industries",
      "Technological",
      "Social",
      "Political",
      "Environmental",
      "Organization",
      "Lifestyles",
      "Healthcare",
    ],
  },
  {
    title: "Source",
    name: "source",
    options: [
      "WSJ",
      "Vanguard News",
      "EV Obsession",
      "EGYPS",
      "World Bank",
      "Zero Hedge",
      "DOE EIA 2013 Energy Conference",
      "Energy.gov Website",
      "African Arguments",
      "Guardian Sustainable Business",
      "Nexus Conference",
      "Sputnik News",
      "khorreports-palmoil",
      "Informed Choice Chartered Financial Planners in Cranleigh",
      "Scientific American",
      "Transport Environment",
      "Biofuels Digest",
      "Technavio",
      "Media Center ",
      "oilprice.com",
      "Resilience",
      "Time",
      "Middle East Eye",
      "PR Newswire",
      "Future Market Insights",
      "maltawinds.com",
      "iamericas",
      "International Banker",
      "bankofcanada",
      "Europa",
      "the star online",
      "Cornell University",
      "arabellaadvisors",
      "Critical Threats",
      "prsync",
      "Politico",
      "Gizmodo Australia",
      "edie.net",
      "Reuters",
      "CNNMoney",
      "gasstrategies",
      "Cars.co.za",
      "dpaq",
      "TeleTrade",
      "Phys Org",
      "EIU",
      "Utility Dive",
      "newscientist",
      "UK Government",
      "World Bank Group",
      "TheCable",
      "Wikipedia",
      "IEA",
      "idc-community",
      "Futureseek Link Digest",
      "Edge and Odds",
      "Environmental Leader",
      "Business Standard",
      "Bloomberg Business",
      "AMERICAN COUNCIL ON SCIENCE AND HEALTH",
      "Yahoo Finance Canada",
      "Gii Research",
      "Climate Change News",
      "South World",
      "The Independent",
      "Nation of Change",
      "Insurance Journal",
      "EY",
      "Eurasia Group",
      "JD Supra",
      "farms",
      "Wells Fargo",
      "Tech Times",
      "3D Printing Progress",
      "Farms.com",
      "The Guardian",
      "satprnews",
      "CNBC ",
      "MRC",
      "nbk",
      "thespanisheconomy",
      "Fitch",
      "Business Insider",
      "controleng",
      "globalmoneytrends",
      "clientadvisoryservices",
      "War on the Rocks",
      "Yes Bank",
      "Rigzone",
      "The Jakarta Post",
      "OklahomaMinerals.com",
      "4th Annual Congress and Expo on Biofuels and Bioenergy April 27-28 2017 Dubai UAE",
      "Fews Net",
      "South Sudan News Agency",
      "",
      "Seeking Alpha",
      "Physics World",
      "The Nation",
      "Euromoney",
      "Carbon Brief",
      "IEA.org",
      "economy",
      "Euler Hermes",
      "CSIS",
      "ebrd",
      "University of Latvia",
      "inputsmonitor",
      "Oxfam",
      "Gartner",
      "NY Times",
      "Think Progress",
      "ogauthority",
      "EIA",
      "Avi Melamed",
      "creamermedia",
      "PDQFX news",
      "FX Empire",
      "THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA",
      "Canadian Biomass",
      "Guarini Center",
      "OMFIF",
      "Triple Pundit",
      "IRENA newsroom",
      "Gas 2",
      "Tactical Investor",
      "University of Chicago",
      "OEM/Lube News",
      "ethicalconsumer",
      "Russia Beyond The Headlines",
      "McKinsey & Company",
      "Sydney Morning Herald",
      "Worldly",
      "Guardian",
      "westpandi",
      "IASTOPPERS",
      "MIT Technology Review",
      "FoodQualityNews.com",
      "The Conversation",
      "PwC",
      "Project Syndicate",
      "Lawfare",
      "unian",
      "Finance Magnates",
      "Future Timeline",
      "iMFdirect - The IMF Blog",
      "Channel News Asia",
      "biomassmagazine",
      "IBEF",
      "sustainablebrands.com",
      "allianzglobalinvestors",
      "SBWire",
      "CleanTechnica",
      "TheNews.NG",
      "FashionNetwork.com",
      "Global Money Trends",
      "World Energy News",
      "Transport Evolved",
      "Peak Prosperity",
      "Business Wire",
      "RiskMap 2017",
      "Adam Curry",
      "Resources for the Future",
      "europeanclimate",
      "Bloomberg New Energy Finance",
      "veteranstoday",
      "biologicaldiversity",
      "portfolioticker",
      "The Economist",
      "ihsmarkit",
      "Planetsave ",
      "IMF",
      "No 2 Nuclear Power",
      "Prospects for Development",
      "TRAC News",
      "Star Tribune",
      "therobotreport",
      "The Next Web",
      "platts",
      "Fox Business",
      "Investopedia",
      "Le·gal In·sur·rec·tion",
      "IFT",
      "Citibank",
      "Future Earth",
      "energyglobal",
      "GE Reports",
      "ESPAS",
      "BorneoPost Online",
      "agriworldsa",
      "Eco-Business.com",
      "Abq",
      "marketrealist",
      "AllAfrica",
      "Convenience Store Decisions",
      "Cii Radio",
      "CBO",
      "News",
      "Vox",
      "cpzulia",
      "BBC News Technology",
      "Wood McKenzie",
      "GreenBiz",
      "www.narendramodi.in",
      "djsresearch",
      "cargill",
      "NWF",
      "USDA",
      "metalprices",
      "Interior Design",
      "The Mainichi",
      "Huffington Post",
      "Drydock Magazine",
      "friday-thinking",
      "Newsweek",
      "Engineering News",
      "nextbigfuture",
      "International Business Times",
      "Wharton",
      "The Chirographer",
      "Slinking Toward Retirement",
      "Wired UK",
      "Imeche",
      "South China Morning Post",
      "Manufacturing Operations Technology Viewpoints",
      "Koenig Investment Advisory",
      "Jachin Capital",
      "Renewable Energy World",
      "Australian Government",
      "THISDAY LIVE",
      "Science Daily",
      "Drill or drop?",
      "amundi",
      "ECFR",
      "African Development Bank",
      "Zawya",
      "FAO",
      "globalizationpartners",
      "Nature",
      "Predictive Analytics Times",
      "valburyresearch",
      "OPEC",
      "Washington Post",
      "LiveMint",
      "Government of Ireland",
      "Energy Tomorrow",
      "FutureinFocus",
      "Fast Co-Exist",
      "Freenewspos",
      "IRENA",
      "International Monetary Fund (IMF)",
      "bankofengland",
      "About Best Binary Options Strategy",
      "U.S. Environmental Protection Agency",
      "Innovate UK",
      "Embedded Computing Design",
      "U.K. Ministry of Defense",
      "Future in Focus",
      "Common Dreams",
      "theicct",
      "Thomson Reuters ",
      "dailytexanonline",
      "Oil and Gas Journal",
      "Infracircle",
      "UNEP",
      "cloudfront",
      "saltlakecityheadlines",
      "CAFrackFacts",
      "Inside Climate News",
      "Countries.com Global Content",
      "UNESCO ",
      "McKinsey Quarterly",
      "ecesr",
      "CIO",
      "Mast",
      "Days Of Year",
      "Maplecroft",
      "ISA",
      "Middle East Online",
      "IER",
      "SlideShare",
      "CCN: Financial Bitcoin & Cryptocurrency News",
      "Newsletter",
      "Global Money Trends Magazine",
      "CAJ News Africa",
      "PriceWaterhouseCoopers",
      "The Arab Gulf States Institute Washington",
      "University Chronicle",
      "globalr2p",
      "worldenergy",
      "Total",
      "knomad",
      "Motor Magazine",
      "HBR",
      "Climate News Network",
      "globalfueleconomy",
      "The Globe and Mail",
      "ReadWrite",
      "Innovaro",
      "What's Next",
      "News.com",
      "nbp",
      "Robothub",
      "Digitalist Magazine",
      "greenerearthnews",
      "uschamber",
      "Aljazeera.com",
      "The Ticker Tape",
      "worldculturepictorial",
      "Neon Nettle",
      "EE News",
      "Before It's News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News",
      "Ocean Acidification",
      "Bearnobull",
      "Global Information Inc",
      "atradius",
      "dailyquiddity",
      "VITA Technologies",
      "Futurity",
      "IHS Engineering 360",
      "Activist Post",
      "Planetizen",
      "Brookings Institute",
      "RUSI",
      "NDTV",
      "Pickens Plan",
      "VOA",
      "Hospitality Trends",
      "Quartz",
      "IISS",
      "The Atlantic",
      "The Market Mogul",
      "GlobalMeatNews.com",
      "g7g20",
      "LNG",
      "European Central Bank",
      "ETEnergyworld.com",
      "briandcolwell",
      "Elsevier",
      "Virgin Atlantic",
      "The Engineer",
      "EPA",
      "Azonano",
      "Wall Street Daily",
      "Arangkada Philippines",
      "European Environment Agency",
      "Scania Group",
      "New Security Beat",
      "betterenergy",
      "Yahoo Finance",
      "conferenceseries",
      "jeita",
      "murc",
      "polymerspaintcolourjournal",
      "njc-cnm",
      "Cushman & Wakefield",
      "MENA-Forum",
      "Nanotechnology Innovation",
      "oilvoice",
      "ethicalmarkets",
      "INSEAD Knowledge",
      "Institutional Investor",
      "Society of Motor Manufacturers and Traders (SMMT)",
      "MAPI",
      "Khaleej Times",
      "Handelsblatt Global Edition",
      "European Council",
      "Atlantic Council ",
      "Australian Government Department of Defence",
      "watercanada",
      "Hardin Tibbs",
      "Verisk Maplecroft",
      "DW.COM",
      "Stanford News",
      "aswm",
      "Shenandoah",
      "National Geographic Society (blogs)",
      "ID TECH INDEX",
      "The Jamestown Foundation",
      "Industry Week",
      "MIT Sloan Management Review",
      "AgWeb - The Home Page of Agriculture",
      "Cushman & Wakefield Blog",
      "Science News",
      "Innovations Report",
      "Blue and Green Tomorrow",
      "Freedonia",
      "Industrial Control Security",
      "Justmeans",
      "Smart Grid Observer",
      "AHDB",
      "savepassamaquoddybay",
      "Business Green",
      "CDC",
      "Strategy & Formerly Booz & Company",
      "Real Estate Professional",
      "Mind Commerce",
      "World Health",
      "Europe in My Region",
      "EPS News",
      "Face2face Africa",
      "Foreign Policy",
      "energy news cyprus",
      "environmentalpeacebuilding",
      "The American Prospect",
    ],
  },
];
